# Generated by Django 4.1.3 on 2022-11-07 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_no', models.IntegerField(default=101)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCoworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('fix', 'Фиксированное рабочее место'), ('room', 'Офис'), ('free', 'Свободное место')])),
                ('price', models.FloatField(default=1000.0)),
                ('amount', models.IntegerField(default=101)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(default=datetime.datetime.now)),
                ('period', models.DateField(default=datetime.datetime.now)),
                ('is_checkout', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.client')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='type_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.typecoworking'),
        ),
    ]
