# Generated by Django 4.1.3 on 2022-11-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_checkout',
        ),
        migrations.RemoveField(
            model_name='typecoworking',
            name='amount',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='typecoworking',
            name='price',
            field=models.FloatField(default=100.0),
        ),
    ]
