# Generated by Django 4.1.3 on 2022-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_remove_reservation_is_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Test', max_length=20, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='Test', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
