# Generated by Django 4.1.3 on 2022-11-07 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_remove_reservation_client_reservation_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='period',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
