# Generated by Django 4.1.3 on 2022-11-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_remove_reservation_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='place',
            name='is_prepared',
            field=models.BooleanField(default=True),
        ),
    ]
